version: '3.1'
volumes:
  data:
services: 
  web:
    build: .
    ports: 
      - 5000:5000
    volumes:
      - .:/project
    depends_on:
      - db
    networks: 
      - net
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql/
    networks: 
      - net
  workdb:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 80:80
    environment: 
      PMA_ARBITRARY: 1  
    networks: 
      - net
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass rootroot
    ports:
      - '6379:6379'
    networks:
      - net

networks:
  net:
    driver: bridge


