"""empty message

Revision ID: 6a9d093f9a7f
Revises: 
Create Date: 2019-04-23 23:10:36.032360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9d093f9a7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_event', sa.String(length=256), nullable=True),
    sa.Column('event_location', sa.String(length=512), nullable=True),
    sa.Column('coverage_area', sa.String(length=64), nullable=True),
    sa.Column('date_start_event', sa.Date(), nullable=True),
    sa.Column('date_end_event', sa.Date(), nullable=True),
    sa.Column('event_description', sa.String(length=2048), nullable=True),
    sa.Column('event_coordinator', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
