"""empty message

Revision ID: ce1451a1b34f
Revises: 
Create Date: 2019-05-02 18:26:32.622696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1451a1b34f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('coverage_area', sa.String(length=64), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('coordinator', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('file', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('coordinator', sa.Integer(), nullable=True),
    sa.Column('belong', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['belong'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appraiser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('in_trail', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['in_trail'], ['trail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('belong', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['belong'], ['trail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist')
    op.drop_table('appraiser')
    op.drop_table('trail')
    op.drop_table('submission')
    op.drop_table('events')
    # ### end Alembic commands ###
